import type { Dispatch, KeyboardEvent, ReactNode, SetStateAction } from 'react'
import { CheckCircle2, Pencil, Plus, Trash2, X } from 'lucide-react'
import { PRIORITY_LABEL, STATUS_LABEL, type EntryFormState } from '../lib/zentraleEntries'
import type { IncidentReport, ZentraleEntry, ZentraleEntryCategory, ZentraleEntryPriority, ZentraleEntryStatus } from '../lib/types'

function formatIncidentOption(item: Pick<IncidentReport, 'reported_at' | 'location' | 'summary'>) {
  const time = new Date(item.reported_at).toLocaleTimeString('de-AT', { hour: '2-digit', minute: '2-digit' })
  return `${time} – ${item.location || item.summary.slice(0, 40)}`
}

// Gemeinsame Bausteine für die generischen zentrale_entries-Kategorien
// (Operative Lage, AV/BV & EV, Fahndungen, Schlüssel, Kontakte, Alarmierung,
// Schichtübergabe, Unterlagen). Wird sowohl von der Zentrale-Hauptseite
// (Übersicht/Einsätze/Lage/Übergabe) als auch von den eigenständigen
// Sidebar-Seiten der übrigen Kategorien verwendet.

export const inputClass = 'mt-1 w-full border border-gray-300 rounded-lg px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500'

export function Empty({ text }: { text: string }) { return <div className="px-5 py-10 text-center"><CheckCircle2 className="w-8 h-8 text-gray-300 mx-auto mb-2" /><p className="text-sm text-gray-500">{text}</p></div> }

export function EntryList({ title, description, entries, canManage, openNew, openEdit, incidentsById, hideCreate }: { title: string; description: string; entries: ZentraleEntry[]; canManage: boolean; openNew: () => void; openEdit: (item: ZentraleEntry) => void; incidentsById?: Record<string, Pick<IncidentReport, 'reported_at' | 'location' | 'summary'>>; /** z. B. Operative Lage: entsteht ausschließlich aus einem Einsatz, kein eigenständiges "Neu" hier. */ hideCreate?: boolean }) {
  return <section className="rounded-2xl border border-gray-200 bg-white overflow-hidden"><div className="px-4 sm:px-5 py-4 border-b bg-gray-50 flex items-center justify-between gap-3"><div><h2 className="font-bold text-gray-900">{title}</h2><p className="text-sm text-gray-500 mt-0.5">{description}</p></div>{canManage && !hideCreate ? <button type="button" onClick={openNew} className="inline-flex items-center gap-2 bg-blue-800 hover:bg-blue-900 text-white text-sm font-medium px-3 py-2 rounded-lg"><Plus className="w-4 h-4" /> Eintrag</button> : null}</div>{entries.length === 0 ? <Empty text="Keine Einträge vorhanden." /> : <div className="divide-y divide-gray-100">{entries.map(item => { const incident = item.incident_id ? incidentsById?.[item.incident_id] : undefined; return <article key={item.id} className="p-4 sm:p-5"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold text-gray-900">{item.title}</h3><span className={`text-xs font-medium px-2 py-0.5 rounded-full ${item.priority === 'kritisch' ? 'bg-red-100 text-red-800' : item.priority === 'hoch' ? 'bg-amber-100 text-amber-800' : 'bg-gray-100 text-gray-600'}`}>{PRIORITY_LABEL[item.priority]}</span><span className="text-xs text-gray-500">{STATUS_LABEL[item.status]}</span>{item.restricted ? <span className="text-xs bg-purple-50 text-purple-700 px-2 py-0.5 rounded-full">Vertraulich</span> : null}</div>{incident ? <p className="text-xs font-medium text-blue-700 mt-1.5">Aus Einsatz: {formatIncidentOption(incident)}</p> : null}{item.description ? <p className="text-sm text-gray-600 mt-2 whitespace-pre-wrap">{item.description}</p> : null}<div className="flex flex-wrap gap-x-4 gap-y-1 text-xs text-gray-400 mt-3">{item.location ? <span>Ort: {item.location}</span> : null}{item.responsible ? <span>Zuständig: {item.responsible}</span> : null}{item.valid_until ? <span>Bis: {new Date(item.valid_until).toLocaleDateString('de-AT')}</span> : null}{item.reference ? <span>Referenz: {item.reference}</span> : null}</div></div>{canManage ? <button type="button" onClick={() => openEdit(item)} className="p-2 text-gray-500 hover:text-blue-700 hover:bg-blue-50 rounded-lg" aria-label="Eintrag bearbeiten"><Pencil className="w-4 h-4" /></button> : null}</div></article> })}</div>}</section>
}

export function Modal({ title, close, children, wide }: { title: string; close: () => void; children: ReactNode; /** Breitere Variante, z. B. für ein Formular mit fest daneben angezeigter Karte. */ wide?: boolean }) { return <div className="fixed inset-0 bg-black/50 z-50 flex items-end sm:items-center justify-center p-3 sm:p-4"><div className={`bg-white rounded-2xl shadow-xl w-full ${wide ? 'max-w-5xl' : 'max-w-2xl'} max-h-[94vh] overflow-y-auto`}><div className="sticky top-0 bg-white z-10 flex items-center justify-between px-5 sm:px-6 py-4 border-b"><h2 className="font-bold text-gray-900">{title}</h2><button type="button" onClick={close} className="p-2 hover:bg-gray-100 rounded-lg" aria-label="Schließen"><X className="w-4 h-4" /></button></div><div className="px-5 sm:px-6 py-4 space-y-4">{children}</div></div></div> }
export function Actions({ saving, close, save }: { saving: boolean; close: () => void; save: () => Promise<void> }) { return <div className="flex justify-end gap-3 pt-2"><button type="button" onClick={close} className="border border-gray-300 text-sm px-4 py-2.5 rounded-lg">Abbrechen</button><button type="button" disabled={saving} onClick={() => void save()} className="bg-blue-800 hover:bg-blue-900 text-white text-sm font-medium px-4 py-2.5 rounded-lg disabled:opacity-60">{saving ? 'Speichern…' : 'Speichern'}</button></div> }
export function Field({ label, value, onChange, type = 'text', disabled, step, onBlur, onKeyDown }: { label: string; value: string; onChange: (value: string) => void; type?: string; disabled?: boolean; step?: string | number; onBlur?: () => void; onKeyDown?: (event: KeyboardEvent<HTMLInputElement>) => void }) { return <label className="block text-xs font-medium text-gray-600">{label}<input type={type} step={step} className={`${inputClass} disabled:opacity-50 disabled:bg-gray-50`} value={value} disabled={disabled} onChange={event => onChange(event.target.value)} onBlur={onBlur} onKeyDown={onKeyDown} /></label> }
export function Area({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="block text-xs font-medium text-gray-600">{label}<textarea className={`${inputClass} min-h-24 resize-y`} value={value} onChange={event => onChange(event.target.value)} /></label> }
export function ErrorMessage({ text }: { text: string }) { return <p className="text-sm text-red-700 bg-red-50 px-3 py-2 rounded-lg">{text}</p> }

export function EntryModal({ entry, setEntry, editing, category, incidents, saving, error, close, save, remove }: { entry: EntryFormState; setEntry: Dispatch<SetStateAction<EntryFormState>>; editing: ZentraleEntry | null; category?: ZentraleEntryCategory; incidents?: Pick<IncidentReport, 'id' | 'reported_at' | 'location' | 'summary'>[]; saving: boolean; error: string; close: () => void; save: () => Promise<void>; remove: () => Promise<void> }) {
  const patch = (values: Partial<EntryFormState>) => setEntry(current => ({ ...current, ...values }))
  // Eine Operative Lage ist kein eigenständiger Bereich - sie entsteht
  // ausschließlich durch "Als Operative Lage erfassen" an einem konkreten
  // Einsatz (siehe Zentrale.tsx openLageForIncident), daher hier nur
  // Anzeige statt einer frei wählbaren Auswahl - der Einsatz steht bereits fest.
  const isLage = (editing?.category ?? category) === 'lage'
  const linkedIncident = isLage ? incidents?.find(item => item.id === entry.incidentId) : undefined
  return <Modal title={editing ? 'Eintrag bearbeiten' : 'Eintrag anlegen'} close={close}>
    {isLage ? <div className="rounded-lg bg-blue-50 border border-blue-200 px-3 py-2 text-sm text-blue-900"><span className="font-medium">Aus Einsatz:</span> {linkedIncident ? formatIncidentOption(linkedIncident) : 'kein Einsatz verknüpft'}</div> : null}
    <Field label="Bezeichnung *" value={entry.title} onChange={value => patch({ title: value })} /><Area label="Beschreibung" value={entry.description} onChange={value => patch({ description: value })} /><div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><label className="text-xs font-medium text-gray-600">Priorität<select className={inputClass} value={entry.priority} onChange={event => patch({ priority: event.target.value as ZentraleEntryPriority })}><option value="normal">Normal</option><option value="hoch">Hoch</option><option value="kritisch">Kritisch</option></select></label><label className="text-xs font-medium text-gray-600">Status<select className={inputClass} value={entry.status} onChange={event => patch({ status: event.target.value as ZentraleEntryStatus })}><option value="offen">Offen</option><option value="in_bearbeitung">In Bearbeitung</option><option value="erledigt">Erledigt</option></select></label><Field label="Gültig ab" type="date" value={entry.validFrom} onChange={value => patch({ validFrom: value })} /><Field label="Gültig bis" type="date" value={entry.validUntil} onChange={value => patch({ validUntil: value })} /><Field label="Ort / Bereich" value={entry.location} onChange={value => patch({ location: value })} /><Field label="Zuständig / Kontakt" value={entry.responsible} onChange={value => patch({ responsible: value })} /></div><Field label="Aktenzeichen, Schlüsselnummer, Telefonnummer oder Link" value={entry.reference} onChange={value => patch({ reference: value })} /><label className="flex items-start gap-2.5 text-sm text-gray-700"><input type="checkbox" className="mt-0.5 rounded" checked={entry.restricted} onChange={event => patch({ restricted: event.target.checked })} /><span><strong>Vertraulich</strong><br /><span className="text-xs text-gray-500">Nur Zentralisten, zuständige Sachbearbeiter und Admins können den Eintrag sehen.</span></span></label>{error ? <ErrorMessage text={error} /> : null}<div className="flex flex-wrap gap-3 pt-2">{editing ? <button type="button" disabled={saving} onClick={() => void remove()} className="mr-auto inline-flex items-center gap-2 text-red-700 text-sm font-medium px-3 py-2.5 rounded-lg hover:bg-red-50"><Trash2 className="w-4 h-4" /> Endgültig löschen</button> : <span className="mr-auto" />}<button type="button" onClick={close} className="border border-gray-300 text-sm px-4 py-2.5 rounded-lg">Abbrechen</button><button type="button" disabled={saving} onClick={() => void save()} className="bg-blue-800 hover:bg-blue-900 text-white text-sm font-medium px-4 py-2.5 rounded-lg disabled:opacity-60">{saving ? 'Speichern…' : 'Speichern'}</button></div></Modal>
}
